{{- range .Values.stages }}
apiVersion: kargo.akuity.io/v1alpha1
kind: Stage
metadata:
  name: {{ .name }}
  namespace: {{ include "kargo-project-gen.name" $ }}
  annotations: {{ toYaml .annotations | nindent 4 }}
spec:
  subscriptions: {{ toYaml .subscriptions | nindent 4 }}
  promotionMechanisms: {{ toYaml .promotionMechanisms | nindent 4 }}
---
{{- end }}