apiVersion: kargo.akuity.io/v1alpha1
kind: Warehouse
metadata:
  name: {{ include "kargo-project-gen.name" . }}
  namespace: {{ include "kargo-project-gen.name" . }}
spec:
  subscriptions: {{ toYaml .Values.warehouse.subscriptions | nindent 4 }}
